# GitHub Pages Configuration
# This file configures Jekyll for GitHub Pages

# Site settings
title: "Vulkan Ray Tracing Tutorial"
description: "A comprehensive tutorial for learning Vulkan ray tracing with practical examples"
baseurl: "" # Leave empty for user/organization sites
url: "" # Leave empty for GitHub Pages

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Plugins (GitHub Pages supported plugins)
plugins:
  - jekyll-relative-links
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Jekyll Relative Links plugin settings
# This automatically converts relative links between .md files
# Links like [doc](setup.md) work on GitHub and are converted to .html for GitHub Pages
relative_links:
  enabled: true
  collections: true

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Include files that start with underscore
include:
  - _pages

# Collections
collections:
  docs:
    output: true
    permalink: /:name/

# Default front matter
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "default"

# Permalink structure
permalink: pretty

# Kramdown settings
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
